version: '3.8'

services:
  chat2api:
    image: lanqian528/chat2api:latest
    container_name: flow-chat2api
    ports:
      - "5005:5005"
    environment:
      # API Key for ChatGPT calls
      - CHATGPT_API_KEY=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
      
      # Authorization for access control
      - AUTHORIZATION=sk-flow-ai-key-2024
      
      # Gateway settings
      - ENABLE_GATEWAY=true
      
      # Basic settings
      - PORT=5005
      - HOST=0.0.0.0
    volumes:
      - chat2api_data:/app/data
    restart: unless-stopped
    networks:
      - flow-network

volumes:
  chat2api_data:

networks:
  flow-network:
    driver: bridge 